#!/bin/bash -e
#
# Copiado de https://github.com/coreos/coreos-baremetal/blob/master/contrib/dnsmasq/get-tftp-files

DEST=tftpboot

if [ ! -d $DEST ]; then
  echo "Creating directory $DEST"
  mkdir -p $DEST
fi

curl -s -o $DEST/undionly.kpxe http://boot.ipxe.org/undionly.kpxe
cp $DEST/undionly.kpxe $DEST/undionly.kpxe.0
