<?php

$config = array(
    'baseurlpath' => 'https://wiki.openstack.sj.ifsc.edu.br/simplesamlphp/',
    'certdir' => '/etc/ssl/certs/',
    'loggingdir' => '/var/log/simplesamlphp/',
    'datadir' => '/var/lib/simplesamlphp/data/',
    'metadatadir' => '/etc/simplesamlphp/metadata/',
    'attributenamemapdir' => '/etc/simplesamlphp/attributemap/',
    'tempdir' => '/tmp/simplesaml',
    'debug' => false,
    'showerrors' => true,
    'errorreporting' => true,
    'debug.validatexml' => false,
    'admin.protectindexpage' => false,
    'admin.protectmetadata' => false,
    'technicalcontact_name' => 'webmaster',
    'technicalcontact_email' => 'webmaster@openstack.sj.ifsc.edu.br',
    'timezone' => 'America/Sao_Paulo',
    'logging.level' => SimpleSAML_Logger::NOTICE,
    'logging.handler' => 'syslog',
    'logging.facility' => defined('LOG_LOCAL2') ? constant('LOG_LOCAL2') : LOG_USER,
    'logging.processname' => 'simplesamlphp',
    'statistics.out' => array(),
    'enable.saml20-idp' => true,
    'enable.shib13-idp' => false,
    'enable.adfs-idp' => false,
    'enable.wsfed-sp' => false,
    'enable.authmemcookie' => false,
    'session.duration' => 8 * (60 * 60),
    'session.datastore.timeout' => (4 * 60 * 60),
    'session.state.timeout' => (60 * 60),
    'session.cookie.name' => 'SimpleSAMLSessionID',
    'session.cookie.lifetime' => 0,
    'session.cookie.path' => '/',
    'session.cookie.domain' => null,
    'session.cookie.secure' => true,
    'session.disable_fallback' => false,
    'enable.http_post' => false,
    'session.phpsession.cookiename' => null,
    'session.phpsession.savepath' => null,
    'session.phpsession.httponly' => false,
    'session.authtoken.cookiename' => 'SimpleSAMLAuthToken',
    'session.rememberme.enable' => false,
    'session.rememberme.checked' => false,
    'session.rememberme.lifetime' => (14 * 86400),
    'language.available' => array(
        'en', 'no', 'nn', 'se', 'da', 'de', 'sv', 'fi', 'es', 'fr', 'it', 'nl', 'lb', 'cs',
        'sl', 'lt', 'hr', 'hu', 'pl', 'pt', 'pt-br', 'tr', 'ja', 'zh', 'zh-tw', 'ru', 'et',
        'he', 'id', 'sr', 'lv', 'ro', 'eu'
    ),
    'language.rtl' => array('ar', 'dv', 'fa', 'ur', 'he'),
    'language.default' => 'pt-br',
    'language.parameter.name' => 'language',
    'language.parameter.setcookie' => true,
    'language.cookie.name' => 'language',
    'language.cookie.domain' => null,
    'language.cookie.path' => '/',
    'language.cookie.lifetime' => (60 * 60 * 24 * 900),
    'attributes.extradictionary' => null,
    'theme.use' => 'default',
    'default-wsfed-idp' => 'urn:federation:pingfederate:localhost',
    'idpdisco.enableremember' => true,
    'idpdisco.rememberchecked' => true,
    'idpdisco.validate' => true,
    'idpdisco.extDiscoveryStorage' => null,
    'idpdisco.layout' => 'dropdown',
    'shib13.signresponse' => true,
    'authproc.idp' => array(
        30 => 'core:LanguageAdaptor',
        45 => array(
            'class'         => 'core:StatisticsWithAttribute',
            'attributename' => 'realm',
            'type'          => 'saml20-idp-SSO',
        ),
        50 => 'core:AttributeLimit',
        99 => 'core:LanguageAdaptor',
    ),
    'authproc.sp' => array(
        90 => 'core:LanguageAdaptor',
    ),
    'metadata.sources' => array(
        array('type' => 'flatfile'),
    ),
    'store.type' => 'phpsession',
    'store.sql.prefix' => 'simpleSAMLphp',
    'metadata.sign.enable' => false,
    'metadata.sign.privatekey' => null,
    'metadata.sign.privatekey_pass' => null,
    'metadata.sign.certificate' => null,
    'proxy' => null,
    'trusted.url.domains' => null,
);

require_once('/var/lib/simplesamlphp/secrets.inc.php');
