# Modificado (arquivo todo)

FROM debian:testing
MAINTAINER Ederson Torresini <boidacarapreta@gmail.com>

RUN	echo "deb http://debian.pop-sc.rnp.br/debian/ testing main contrib non-free" > /etc/apt/sources.list && \
	echo "deb http://security.debian.org/ testing/updates main contrib non-free" >> /etc/apt/sources.list && \
	apt-get update && \
	apt-get -y upgrade && \
	apt-get install -y memcached && \
	apt-get install -y php5-mysql && \
	apt-get install -y php5-intl && \
	apt-get install -y php5-gd && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

CMD ["memcached","-u","memcache","-m","256"]
