FROM debian:testing
MAINTAINER Ederson Torresini <boidacarapreta@gmail.com>

RUN	echo "deb http://debian.pop-sc.rnp.br/debian/ testing main contrib non-free" > /etc/apt/sources.list && \
	echo "deb http://security.debian.org/ testing/updates main contrib non-free" >> /etc/apt/sources.list && \
	apt-get update && \
	apt-get -y upgrade && \
	apt-get -y install haproxy && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

CMD ["haproxy","-f","/etc/haproxy/haproxy.cfg"]
