# Modificado (arquivo todo)

FROM debian:testing
MAINTAINER Ederson Torresini <boidacarapreta@gmail.com>

RUN	echo "deb http://debian.pop-sc.rnp.br/debian/ testing main contrib non-free" > /etc/apt/sources.list && \
	echo "deb http://security.debian.org/ testing/updates main contrib non-free" >> /etc/apt/sources.list && \
	apt-get update && \
	apt-get -y upgrade && \
	apt-get install -y zlib1g-dev && \
	apt-get install -y libpcre3-dev && \
	apt-get install -y build-essential && \
	apt-get install -y git && \
	git clone https://github.com/nginx-shib/nginx-http-shibboleth.git /usr/local/src/nginx-http-shibboleth && \
	apt-get install -y mercurial && \
	hg clone http://hg.nginx.org/nginx /usr/local/src/nginx && \
	(cd /usr/local/src/nginx && auto/configure --sbin-path=/usr/local/sbin --conf-path=/etc/nginx --add-module=/usr/local/src/nginx-http-shibboleth && make && make install) && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

CMD ["nginx"]
