#!/bin/sh

# Diretório comum (ClusterFS)
DIR="/media/wall0/php-fpm/sessions/"
[ -d ${DIR} ] || exit 1

# Arquivos vazios (sessões não iniciadas) há mais de 1 dia
find ${DIR} -type f -size 0c -mtime +1 -delete

# Sessões iniciadas e não autenticadas (pelo IdP) há mais de 1 dia
find ${DIR} -type f -size 521c -mtime +1 -delete

# Sessões autenticadas há mais de 1 mês
find ${DIR} -type f -mtime +30 -delete
